### PR TITLE
Add a REST server with FastAPI

### LINKED ISSUE #38: Finalize TQEC REST API
Currently, both the frontend (javascript UI / code) and the backend (Python code) are separate pieces of code that do not interact with each other. 

The currently envisioned process to create a QEC experiment is the following:
1. The user starts the frontend.
2. The user builds the experiment he/she wants to perform, still 100% in the frontend.
3. Once the experiment is fully caracterised in the frontend, the user asks for the `Stim` file generation (or multiple `Stim` files).
4. [internally] the frontend represents the QEC experiment in a JSON format.
5. [internally] the frontend sends the generated JSON to the backend (Python code).
6. [internally] the backend generates a `Stim` file from the input JSON.
7. [internally] the backend sends back the generated `Stim` file to the frontend.
8. The frontend provides a way to download / export the generated `Stim` file.

The above process is still in discussion. It has shortcomings, but also has the good property of being really simple to implement on both sides (frontend and backend).

The current communication scheme using JSON, both the frontend and backend need to agree on the JSON format.
A tentative format can be found in the [`specification/schemas`](https://github.com/QCHackers/tqec/tree/main/specification/schemas) folder. We would like to improve this format and actually implement the serialisation / deserialisation procedures in both the frontend and the backend.

### PR DESCRIPTION
**Pull request by nelimee**
This is a draft PR trying to implement a REST server on the backend side.

This is the initial implementation that will allow a link between the frontend and the backend. 

Currently, the idea is the following: all the QEC-related state is stored in the backend and the frontend is making requests through the provided REST API to 1. query the current QEC state or 2. change it. 
Here, "QEC-related state" means that:
- the frontend will **not** store the plaquettes, it will rather query the backend to have a description of the currently implemented plaquettes when needed,
- the frontend will **not** store the templates, it will rather query the backend to have a description of the currently implemented plaquettes when needed, 

Because we want to avoid a communication at each user inputs, the frontend may store partial state.

Note that everything I wrote above and the code from this PR is a proposal, I am very much open to any other idea if it turns out to be easier to use.

To use the code from that PR and experiment with the REST server, follow the instructions:
1. checkout the branch from that PR (https://github.com/nelimee/tqec/tree/feat/fast-api-rest),
2. re-install the `tqec` package to get the new dependencies
    ```sh
    python -m pip install -e ./
    ```
    or install the added dependencies directly
    ```sh
    python -m pip install pydantic fastapi
    ```
3. Start the REST server with
    ```sh
    fastapi dev ./web/server.py
    ```
4. If everything succeeded, you can access the server on http://127.0.0.1:8000/ (try out http://127.0.0.1:8000/templates/list or http://127.0.0.1:8000/plaquettes/list). The REST api documentation is available at http://127.0.0.1:8000/docs.

### Related issues:

- #170: if the decision to pursue in the direction explained above is taken, the backend will be responsible for that, and already implement the feature.
- #169: the backend would become responsible for the generation of the file, the frontend will still need to provide a way to save the file to the user.
- #61: nicely handled by using `pydantic` and implementing methods to convert from/to the defined `pydantic.BaseModel`.
- #38: the main related issue, this PR try to fix #38.
- #18: this PR introduces the possibility to export to Stim files, and so should fix that issue.

### CODE REVIEW

**Comment by Gistbatch** [comment]
Just as a reminder:
We already had a Flask server in place, which was initially set up by @smburdick, and the front end has some unused functionality.
The file server root is in `/web/main.py`, also deployed to gcloud.
I don't have any strong preference between `flask` and `fastapi`, and most of the concepts are very similar.

- From a dev perspective, we might eventually think about hosting a proper database, which is straightforward with Pydantic.
- If we plan to host the backend and the frontend on different sites, we also need to enable `CORS`
- We should start to think about what information needs to be transferred at which points in time
- Also we should set up a proper structure for the webserver

**Comment by nelimee** [comment]
I have no personal preference on that. As I already said multiple times, I am not competent for web-related development task (and I try to stay as far away as possible from anything related to web-technologies). 

My choice of `pydantic` + `fastapi` was based on the easy of use of `pydantic` and the ultra-fast integration of `fastapi` once you have `pydantic` models in place. There is really no smart thinking that happened on my side, an I will adopt whatever is judged to be the best solution by others. 

Let's consider this PR as a playground to start exploring the integration between the frontend and backend, and see what is required from both sides. At any time (if possible, early), if the choice of `pydantic` + `fastapi` seems worse than another library, please tell me, or change the framework directly.

**Comment by nelimee** [comment]
I will resolve all the conflicts and push to a repository branch in the afternoon.

**Comment by nelimee** [comment]
Replaced by #240

**Pull request closed without merging**
