### PR TITLE
Fix bugs when deleting cloned plaquettes; restructure workspace and control panel; add basic UI for plaquette cloning

### PR DESCRIPTION
**Pull request by smburdick**
Address #24 

Conversation in that issue needs to be spun off into another issue -- in particular, address why `this._geometry` is null when selecting a plaquette and deleting it.

### CODE REVIEW

**Review by rryoung98 — CHANGES_REQUESTED** [review]
Thanks for the PR @smburdick  

The buttons are really helpful!

I believe after todays conversation, that it's important to think about the basic UI more. 

First I'll outline the pros and cons of the two methods proposed here I think having both is vital for now to make sure we can work quickly:

1. Drag and create
**Pro:** 
- It's considerably faster when the graphics are repetitive.
**Con:**
- The drag is buggy (Though I believe it can be fixed and added additional notification for the user).
- It's not immediately intuitive (especially in its current state where there are not enough instructions).
- Deleting graphics issue (should be spun out into a separate issue outside of the UI since both implementations have this issue).

2. Arrows
**Pro:** 
- Much more explicit
- Great for testing
**Con:**
- It takes a while to click on individual shapes over and over. (this can be improved too)
- Still has the ._geometry null bug. 


Can we keep both for now and try and fix the above Cons? This is just a function of putting in time to make the UI perfect for both methods.

**Comment by smburdick** [comment]
@rryoung98 I agree with your assessments, and have restored the ability to drag-copy.

Do we want to address the `._geometry` null bug in this PR as well?

I've had some success deleting copied plaquettes, when they were spawned through the control panel, but not so when copied by dragging.

There are some lingering bugs with copying (when both styles are mixed). For example: sometimes, I cannot make a copy of a copied plaquette.

I also agree that several issues here should be tracked separately.

**Comment by rryoung98** [comment]
Hmmm. That's up to you, but fixing .geometry takes priority. I've added some ideas on how to fix it to the issue. I will tackle it this weekend if not finished.

**Comment by smburdick** [comment]
@rryoung98 I'll take a look at the geometry issue as well (starting tomorrow) and will keep this PR open.

**Comment by smburdick** [comment]
Addressing #24 in latest commit here.

**Comment by smburdick** [comment]
Notably, plaquettes spawned unintentionally still cannot be deleted, but can if done through the control panel.

**Review by rryoung98 — COMMENTED** [review]
This is a pretty good start nice adds still some work to do to make sure the plaquettes are deleted properly and the dragging functionality is fixed.

Nice work :)

**Review by rryoung98 — APPROVED** [review]

**Pull request merged**
