### PR TITLE
🎨 🐛 Memory experiment on logical qubit works!

### PR DESCRIPTION
**Pull request by nelimee**
This commit finally succeed in replicating the results from Stim for the surface code encoding a simple logical qubit.

### CODE REVIEW

**Comment by afowler** [comment]
Excellent :-)

**Review by smburdick — COMMENTED** [review]
Continuing our conversation from before -- are the functions in this notebook purely experimental, or will they be merged into the backend (`tqec/`) for further use?

**Comment by nelimee** [comment]
This notebook is considered like a functional test as it compares the outputs obtained by the `tqec` library to the outputs of `stim`, considered as the ground-truth.

**Comment by rryoung98** [comment]
woop!

**Review by smburdick — APPROVED** [review]
Based on https://github.com/QCHackers/tqec/pull/28#issuecomment-1881785559, seems good to me.

**Pull request merged**
