### PR TITLE
Improve `subtemplates`

### PR DESCRIPTION
**Pull request by nelimee**
This PR:

- ~~bumps `numpy` version explicitly in the requirements to only support `numpy ~= 2.0`,~~ not anymore, see comments,
- improves the documentation of `tqec.templates.subtemplates`,
- performs some minor `import` linting (removing unused, ordering, only relative imports in the main `__init__.py`).

### CODE REVIEW

**Comment by inmzhang** [comment]
`Pymatching` still does not support `numpy2`? https://github.com/oscarhiggott/PyMatching/issues/102

**Comment by nelimee** [comment]
> `Pymatching` still does not support `numpy2`? [oscarhiggott/PyMatching#102](https://github.com/oscarhiggott/PyMatching/issues/102)

That seems to be true, good catch, I am rolling back the version bump on numpy.

**Review by inmzhang — APPROVED** [review]
Based on the timing, I think it's efficient enough? After all, the realistic `k`s we simulate for should be upper bounded by 10~14.

**Comment by nelimee** [comment]
> Based on the timing, I think it's efficient enough? After all, the realistic `k`s we simulate for should be upper bounded by 10~14.

Yes, I agree.

**Pull request merged**
