### PR TITLE
Usage

### PR DESCRIPTION
**Pull request by Gistbatch**
We need instructions on how to use our library.
This is the first draft of a `Usage` file.

### CODE REVIEW

**Comment by KabirDubey** [comment]
Should I make an issue requiring`usage.md` file and examples folder from the 8/21 meeting? This PR can link to it

**Comment by afowler** [comment]
I think that would be a good idea :-)

**Comment by nelimee** [comment]
A few notes on that issue:

- The workflow is schematized in the image in #299. From that, we are only missing clear notebooks / documentation to let the user understand how to navigate forward in this workflow.
- Currently, all the notebooks using plaquettes are broken. This is due to the fact that we removed hand-written detectors in plaquette definitions in a previous commit and do not have yet an efficient way of re-including them automatically without changing slightly the notebooks code. 
- Having command lines that can export things would be nice. For example, `tqec_find_observable -i computation.dae --out-dir observables/` that would populate the `observables` directory with images representing all the observables found by the tool.

**Comment by Gistbatch** [comment]
@nelimee We are trying to show a simple example of going from a `.dae` file to a stim circuit.
I tried to implement the following:
```python
block_graph = BlockGraph.from_dae_file("./tests/resources/simple_exp.dae")
circuit = block_graph.to_circuit(LinearFunction(2, 0))
stimcirq_circuit = cirq_circuit_to_stim_circuit(
    transform_to_stimcirq_compatible(circuit)
)
with tempfile.TemporaryDirectory() as temp_dir:
    output_file = Path(temp_dir) / "output.stim"
    stimcirq_circuit.to_stim(output_file)
    assert output_file.exists()
```
on my branch for #298.
`simple_exp.dae` contains a truncated part of `clean_exportable_cnot.skp` of two blocks and a pipe at the origin.
This fails at the stimcirq conversion. Do you have any idea what is going on?

**Comment by nelimee** [comment]
> @nelimee We are trying to show a simple example of going from a `.dae` file to a stim circuit.
> I tried to implement the following:
> ```python
> block_graph = BlockGraph.from_dae_file("./tests/resources/simple_exp.dae")
> circuit = block_graph.to_circuit(LinearFunction(2, 0))
> stimcirq_circuit = cirq_circuit_to_stim_circuit(
>     transform_to_stimcirq_compatible(circuit)
> )
> with tempfile.TemporaryDirectory() as temp_dir:
>     output_file = Path(temp_dir) / "output.stim"
>     stimcirq_circuit.to_stim(output_file)
>     assert output_file.exists()
> ```
> on my branch for #298.
> `simple_exp.dae` contains a truncated part of `clean_exportable_cnot.skp` of two blocks and a pipe at the origin.
> This fails at the stimcirq conversion. Do you have any idea what is going on?

Could you provide me the error encountered as well ?

**Comment by Gistbatch** [comment]
I run this from a test:
```
=================================== FAILURES ===================================
_______________________________ test_end_to_end ________________________________
    def test_end_to_end() -> None:
        block_graph = BlockGraph.from_dae_file("./tests/resources/single_block.dae")
        circuit = block_graph.to_circuit(LinearFunction(2, 0))
>       stimcirq_circuit = cirq_circuit_to_stim_circuit(
            transform_to_stimcirq_compatible(circuit)
        )

src/tqec/sketchup/block_graph_test.py:157: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/lib/python3.12/site-packages/stimcirq/_cirq_to_stim.py:93: in cirq_circuit_to_stim_circuit
    return cirq_circuit_to_stim_data(circuit, q2i=qubit_to_index_dict, flatten=False)[0]
.venv/lib/python3.12/site-packages/stimcirq/_cirq_to_stim.py:114: in cirq_circuit_to_stim_data
    helper.process_moments(circuit)
.venv/lib/python3.12/site-packages/stimcirq/_cirq_to_stim.py:494: in process_moments
    self.process_moment(moment)
.venv/lib/python3.12/site-packages/stimcirq/_cirq_to_stim.py:486: in process_moment
    self.process_operations(moment)
.venv/lib/python3.12/site-packages/stimcirq/_cirq_to_stim.py:436: in process_operations
    custom_method(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = tqec.circuit.operations.operation.RX((cirq.GridQubit(3, 5),))
edit_circuit = stim.Circuit('''
    QUBIT_COORDS(0, 4) 0
    QUBIT_COORDS(0, 8) 1
    QUBIT_COORDS(1, 1) 2
    QUBIT_COORDS(1, 3) 3
 ...4 0 38 45 36 44 4 2 48 27 30 12 39 20 34 14 29 15 47 17 33 25 32 1 26 13 31 23 43 18 8 42 16 35
    TICK
    R 0 7
''')
kwargs = {'dont_forget_your_star_star_kwargs': True, 'edit_measurement_key_lengths': [('q(6, 2)', 1), ('q(2, 0)', 1), ('q(8, 8)', 1), ('q(2, 8)', 1), ('q(2, 6)', 1), ('q(2, 4)', 1), ...], 'have_seen_loop': True, 'targets': [14]}

    def _stim_conversion_(
        self, edit_circuit: stim.Circuit, **kwargs: dict[str, typing.Any]
    ) -> None:
>       edit_circuit.append_operation("RX", list(self.qubits), None)
E       ValueError: target argument wasn't a qubit index, a result from a `stim.target_*` method, or a `stim.GateTarget`.

src/tqec/circuit/operations/operation.py:408: ValueError
```

**Comment by nelimee** [comment]
Yes I mande a mistake when implementing a custom operation, I will fix this tomorrow ! Thanks for letting me know.

**Comment by Gistbatch** [comment]
closed in favor of #321 see #325

**Pull request closed without merging**
