### PR TITLE
Relocate alternative frontend

### PR DESCRIPTION
**Pull request by smburdick**
The alternative frontend now lives at https://github.com/QCHackers/tqec-alternative-frontend.

Related: #212

### CODE REVIEW

**Comment by vtomole** [comment]
Why the relocation? Is this on the way to merging the projects?

**Comment by smburdick** [comment]
> Why the relocation? Is this on the way to merging the projects?

It is indeed.

**Review by vtomole — APPROVED** [review]
LGTM

**Comment by vtomole** [comment]
@giangiac I think the plan is to cherry pick the important changes from the alternative frontend and wisely merge them to the existing one; which is already under way by @smburdick

**Comment by smburdick** [comment]
> @giangiac I think the plan is to cherry pick the important changes from the alternative frontend and wisely merge them to the existing one; which is already under way by @smburdick

I thought having two frontends would be confusing for newcomers.

The alternative frontend is preserved at  https://alt-tqecjs-421617.wl.r.appspot.com/ and https://github.com/QCHackers/tqec-alternative-frontend

I've already cherry picked the features into https://tqec.app (this repo frontend)

**Comment by giangiac** [comment]
I believe we discussed in the weekly call to provide both frontends since they have different features.

I understand that it may be confusing having two frontends if we agree that:
1) one design is clearly superior and the other just a distraction
2) or if the TQEC community has no bandwidth to pursue more than one approach.

There can be a case for 2) since only a handful of members are contributing to the frontend.
Concerning 1), the situation is less clear for me. The current frontend has a more professional codebase (good coding practices, enhanced security, ...) while the alternative one offers more functionalities.

**Comment by smburdick** [comment]
> I believe we discussed in the weekly call to provide both frontends since they have different features.
> 
> I understand that it may be confusing having two frontends if we agree that:
> 
> 1. one design is clearly superior and the other just a distraction
> 2. or if the TQEC community has no bandwidth to pursue more than one approach.
> 
> There can be a case for 2) since only a handful of members are contributing to the frontend. Concerning 1), the situation is less clear for me. The current frontend has a more professional codebase (good coding practices, enhanced security, ...) while the alternative one offers more functionalities.

@giangiac See my above comment (you may not have received the email):
> The alternative frontend is preserved at https://alt-tqecjs-421617.wl.r.appspot.com/ and https://github.com/QCHackers/tqec-alternative-frontend

**Comment by smburdick** [comment]
Alternatively, http://tqec2live.org.

**Pull request merged**
