### PR TITLE
Improve CI and include coverage data

### PR DESCRIPTION
**Pull request by nelimee**
This PR aims at improving the CI build times and including an automatic report on code coverage.

### CODE REVIEW

**Comment by nelimee** [comment]
Lead for why this might be failing: https://github.com/marocchino/sticky-pull-request-comment/issues/930

**Review by inmzhang — APPROVED** [review]
I try to test the actions locally with [`act`](https://github.com/nektos/act) but encounter some network issues. So currently I'm not able to verify this PR and I'll just approve it.

**Comment by nelimee** [comment]
So right now it does not work and I have no way of testing that correctly without pushing to `main` as the `workflow_run` event needs to be on the default branch to run. I will try to find another way of doing that.

**Comment by nelimee** [comment]
Closing in favour of a PR from a branch from the `QCHackers` group

**Pull request closed without merging**
