### PR TITLE
Validate `ComposedTemplate`

### LINKED ISSUE #242: Validate `ComposedTemplate`
**Is your feature request related to a problem? Please describe.**
Some instances of `ComposedTemplate` are invalid when scaled up. For example,
image
will eventually be invalid as, when `k` grows, the two scalable templates at the bottom will eventually overlap.

It would be nice to be able to check that kind of problems directly within the `ComposedTemplate` class and return a nice error message when an error is found.

**Describe the solution you'd like**
Following #241, and assuming that template bounding boxes cannot overlap (which might not be valid if we have a `ComposedTemplate` instance containing non-atomic templates, such as other `ComposedTemplate` instances), we might be able to compute if two template might eventually overlap from their scalable bounding box. 
If such a case happens, an error should be raised.

### PR DESCRIPTION
**Pull request by nelimee**
This PR implements the necessary classes and functions to be able to validate any `ComposedTemplate` instance. Here, validating means checking that, for any possible input `k`, the `ComposedTemplate` instance will not overlap with itself.

Closes #242

### CODE REVIEW

**Comment by nelimee** [comment]
I just realised that a lot of documentation was missing, I will add it before asking for another review.

**Comment by nelimee** [comment]
Since last review, I added documentation, fixed some edge cases and allowed `Interval` instances to explicitly know whether or not each boundary should be considered included in the interval or excluded from it.

I think this is ready for review.

**Review by inmzhang — APPROVED** [review]
LGTM. Just wanted to mention that, I found a package [`portion`](https://github.com/AlexandreDecan/portion?tab=readme-ov-file#interval-operations) that appear to do something similar to `Interval`.

**Comment by nelimee** [comment]
> LGTM. Just wanted to mention that, I found a package [`portion`](https://github.com/AlexandreDecan/portion?tab=readme-ov-file#interval-operations) that appear to do something similar to `Interval`.

This package seems way better than my hand-written solution! I would like to use it instead of my custom-wrote code that is very likely way less robust. Do you think I should do that in this PR or in another one?

**Pull request merged**
