### PR TITLE
Get alternative frontend back in the codebase

### PR DESCRIPTION
**Pull request by giangiac**

### CODE REVIEW

**Comment by vtomole** [comment]
@giangiac Can't we just make this the main frontend now since the people that we working on the on the other front-end are not contributing anymore?

**Comment by giangiac** [comment]
> @giangiac Can't we just make this the main frontend now since the people that we working on the on the other front-end are not contributing anymore?

That is the goal, but I did not want to "break" what Sam put in place. For example accessing the frontend at https://tqec.app/
(note that my company blocks access to that website, so I cannot confirm if it still works).

If we "swap" the frontends, do you know who can update that webpage?

**Comment by vtomole** [comment]
I think only Sam has the permissions to push updates to that site.

**Comment by afowler** [comment]
At this stage we have unfortunately lost Sam to health issues, so we will
need to find another way that doesn't rely on Sam.

**Comment by giangiac** [comment]
@vtomole @afowler 
What about these steps?
- merge this PR so that the frontend v2 [what we called the alternative frontend and should be the official frontend moving forward] returns to the main TQEC repo in folder `<repo>/ggg_frontend`
- merge latest development to the frontend v2 [from Gian's fork]
- create another PR to move frontend v1 to `<repo>/old_frontend`, and move frontend v2 to `<repo>/frontend`
- find a way to update the tqec website

**Comment by vtomole** [comment]
@giangiac  Sounds good to me!

**Comment by giangiac** [comment]
> @giangiac Sounds good to me!

Perfect.
Please go ahead and merge this PR to complete the first bulletpoint of the plan.
(I cannot merge myself)

**Review by vtomole — APPROVED** [review]
LGTM

**Comment by vtomole** [comment]
@giangiac I just approved the PR. Can you merge now?

**Comment by giangiac** [comment]
Yes, I was able to merge.

Please check #265 to continue with step 2 of the 4-step plan discussed above.

**Pull request merged**
