### PR TITLE
Educational: step-by-step coding of the frontend

### PR DESCRIPTION
**Pull request by giangiac**
Hi TQEC friends,

I am unfamiliar with JavaScript, React, Pixi, ... but would like to help developing the frontend part.
I opted for a hands-on approach to learn those language & libraries, with the side benefit of familiarizing with the frontend codebase.

I started by setting up a template React project with:
https://create-react-app.dev/
and then continued by adding snippets of code from the tqecjs frontend:
https://github.com/giangiac/tqec/tree/test-frontend/step-by-step-frontend

I noticed that this may be helpful to the community members who, like me, need to learn the basics of a web app.
If there is interest, I can create a PR to track the extension of the "step-by-step frontend coding", with the commit message indicating the functionality added by each of them.
Checking the commit content will help locating the part of code responsible for that functionality.

### CODE REVIEW

**Comment by smburdick** [comment]
@giangiac If you'd like, you can go ahead and open this PR.

One thing I noticed was that the commit history shows you the tutorial steps for building up the frontend piece-by-piece.

**Comment by giangiac** [comment]
**Comments on the differences with the original frontend**

- instead of qubits, the initial white circles are "positions" where the qubits may be added
- clicking a position adds a qubits there
- when a plaquette is created, qubits are added to it
- instead of dragging the plaquette around, I opted for a button to move it to predefined areas
- the plaquette's qubits are moved accordingly, thus freeing the option to add new qubits in the plaquette-building area for the next plaquette

**Comment by smburdick** [comment]
@giangiac I think your work here is also addressing #46, which is essential to the main app, on top of having this educational tool for newcomers. Would you be able to spin off the circuit builder into a separate branch, and open a pull request for that specific issue?

**Comment by giangiac** [comment]
> @giangiac I think your work here is also addressing #46, which is essential to the main app, on top of having this educational tool for newcomers. Would you be able to spin off the circuit builder into a separate branch, and open a pull request for that specific issue?

Sam, I'll create a separate PR with the relevant code.

**Comment by rryoung98** [comment]
hi @giangiac  and @smburdick  I looked at your step-by-step branch and it's great! thank you @giangiac. I'm thinking of getting started with the connection between frontend and backend. Do you want me to wait until the new pr is made?

**Comment by smburdick** [comment]
> hi @giangiac and @smburdick I looked at your step-by-step branch and it's great! thank you @giangiac. I'm thinking of getting started with the connection between frontend and backend. Do you want me to wait until the new pr is made?

@rryoung98 Are you referring to https://github.com/QCHackers/tqec/issues/38?

**Comment by giangiac** [comment]
> hi @giangiac and @smburdick I looked at your step-by-step branch and it's great! thank you @giangiac. I'm thinking of getting started with the connection between frontend and backend. Do you want me to wait until the new pr is made?

Thanks, @rryoung98!
I have no clue how to connect the JS frontend with the Python backend. One "cheap" option is that the backend simply parses the .txt file with the library of plaquettes/circuits and take over from there. Effectively, this means two separate "programs/apps" that just agree on the output/input file format.

Is there a way to have a deeper integration?
How do you envision that?

An idea (not sure how realistic) may be having multiple "tabs" in the webapp. The first tab being the frontend, then the user can switch to other tabs for the template creation, etc etc. The code enabling the frontend functionalities (and thus the other tabs) is in Python, so I am not sure how/if that works.

**Comment by smburdick** [comment]
> > hi @giangiac and @smburdick I looked at your step-by-step branch and it's great! thank you @giangiac. I'm thinking of getting started with the connection between frontend and backend. Do you want me to wait until the new pr is made?
> 
> Thanks, @rryoung98! I have no clue how to connect the JS frontend with the Python backend. One "cheap" option is that the backend simply parses the .txt file with the library of plaquettes/circuits and take over from there. Effectively, this means two separate "programs/apps" that just agree on the output/input file format.
> 
> Is there a way to have a deeper integration? How do you envision that?
> 
> An idea (not sure how realistic) may be having multiple "tabs" in the webapp. The first tab being the frontend, then the user can switch to other tabs for the template creation, etc etc. The code enabling the frontend functionalities (and thus the other tabs) is in Python, so I am not sure how/if that works.

@giangiac You're spot on, actually -- the frontend and backend communicate via REST APIs, using a predetermined JSON schema.

Your idea was sketched up in one of our design files in the shared Gdrive, but I don't think we've looked into those as a group lateley.

**Comment by rryoung98** [comment]
Yes, it's going to be just rest apis with json (we will need to tweak your ascii circuits into something easier to parse like qasm).

**Comment by smburdick** [comment]
Marking this as closed -- @giangiac

**Pull request closed without merging**
