### PR TITLE
Fix installation of tqec package

### LINKED ISSUE #35: Python package installation is broken in non-editable mode
The Python package installation only works in editable mode (`python -m pip -e`).

Installing from scratch the `tqec` package with:
```bash
# In an active and freshly created virtual environment.
cd tqec
python -m pip install .
python -m pip install jupyterlab sinter pymatching
```
and trying to run any of the notebooks by running
```bash
python -m jupyter lab
```
will output a module not found error at the first `tqec` import:
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 7
      4 import stim
      5 from stimcirq import cirq_circuit_to_stim_circuit
----> 7 from tqec.constructions.qubit import ScalableQubitSquare
      8 from tqec.detectors.gate import ShiftCoordsGate
      9 from tqec.detectors.transformer import fill_in_global_record_indices

ModuleNotFoundError: No module named 'tqec.constructions'
```

### PR DESCRIPTION
**Pull request by nelimee**
This PR fixes #35 and maybe #56 (I cannot replicate this one).

### CODE REVIEW

**Comment by nelimee** [comment]
Also, this PR will basically block every other contributions I make to the actual code as it changes the place where the code lies from `tqec` to `src/tqec` and I do not want to have to deal with merging this one with other code changes.
As such, it would be nice if you agree to merge it soon.

**Review by vtomole — COMMENTED** [review]
Cosmetic issue: Why have an `src` directory? https://github.com/quantumlib/OpenFermion/issues/562

**Comment by nelimee** [comment]
Ok I did not read the final message of your issue. I would argue that avoiding accidental path-based imports is a strong incentive to the `src` layout.

**Review by smburdick — APPROVED** [review]
Fantastic -- this could address @afowler 's concerns too in #56

**Comment by nelimee** [comment]
I'll also wait for @vtomole answer or validation on that too, I do not want to merge with pending discussion.

**Comment by vtomole** [comment]
I'll respond in a day or two after doing my research :)

**Review by vtomole — APPROVED** [review]
Reasons for `src` sound good to me!

**Pull request merged**
