### PR TITLE
Canonical form circuit builder

### PR DESCRIPTION
**Pull request by smburdick**
* User can specify ancilla, measure, CX|CZ qubits in a plaquette
* Print out ASCII form to console when done

Demo: https://drive.google.com/file/d/1yChGhv0ErEw5g9OsJp4cRlKj_izdvWBQ/view?usp=sharing

### CODE REVIEW

**Comment by Gistbatch** [comment]
Suggested changes from the call today:

- Ancilla and Measure are synonyms
- ASCII code is not formatted correctly; I assume the console is not in a monospace font
- "Cycle" through X and Z qubits in the plaquette

**Comment by smburdick** [comment]
> Suggested changes from the call today:
> 
> * Ancilla and Measure are synonyms

Will remove specification of M

> * ASCII code is not formatted correctly; I assume the console is not in a monospace font

It is, but I should use more consistent formatted strings to achieve the results we want.

> * "Cycle" through X and Z qubits in the plaquette

Will replace individual CX and CZ flows with a singe CX/CZ flow.

**Review by rryoung98 — APPROVED** [review]
Haven't tested but let's expedite this so we can unblock the frontend migration

**Comment by smburdick** [comment]
> Haven't tested but let's expedite this so we can unblock the frontend migration

OK, I'll open an issue for my/@Gistbatch's discussion.

**Pull request merged**
